import 'dart:io';
import 'package:flutter/material.dart';
import 'package:multigateway/app/translate/tl.dart';
import 'package:multigateway/core/chat/chat.dart';
import 'package:multigateway/features/home/presentation/widgets/chat_message_widgets/animated_avatar_border.dart';
import 'package:multigateway/features/home/presentation/widgets/chat_message_widgets/animated_markdown.dart';
import 'package:multigateway/features/home/presentation/widgets/chat_message_widgets/message_version_switcher.dart';
import 'package:multigateway/features/home/presentation/widgets/chat_message_widgets/reasoning_dropdown.dart';
import 'package:multigateway/shared/utils/theme_aware_image.dart';

/// Widget hiển thị tin nhắn của trợ lý AI
class AssistantMessageCard extends StatelessWidget {
  final ChatMessage message;
  final bool isStreaming;
  final VoidCallback? onCopy;
  final VoidCallback? onEdit;
  final VoidCallback? onDelete;
  final VoidCallback? onRegenerate;
  final VoidCallback? onRead;
  final Function(int)? onSwitchVersion;

  const AssistantMessageCard({
    super.key,
    required this.message,
    this.isStreaming = false,
    this.onCopy,
    this.onEdit,
    this.onDelete,
    this.onRegenerate,
    this.onRead,
    this.onSwitchVersion,
  });

  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.centerLeft,
      child: GestureDetector(
        onLongPressStart: (details) =>
            _showContextMenu(context, details.globalPosition),
        child: ConstrainedBox(
          constraints: const BoxConstraints(maxWidth: 760),
          child: Container(
            margin: const EdgeInsets.symmetric(vertical: 8),
            padding: const EdgeInsets.all(8),
            color: Colors.transparent,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // Top row: avatar (left) + read button (right)
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    AnimatedAvatarBorder(
                      isAnimating: isStreaming,
                      radius: 18,
                      child: const CircleAvatar(
                        radius: 18,
                        child: Icon(Icons.token, size: 18),
                      ),
                    ),
                    if (onRead != null)
                      IconButton(
                        visualDensity: VisualDensity.compact,
                        iconSize: 18,
                        icon: const Icon(Icons.volume_up),
                        tooltip: tl('Read'),
                        onPressed: onRead,
                      ),
                  ],
                ),

                // Content
                if ((message.content ?? '').trim().isNotEmpty)
                  Padding(
                    padding: const EdgeInsets.only(top: 6),
                    child: AnimatedMarkdown(content: message.content ?? ''),
                  ),

                // Media generated by AI
                if (message.files.isNotEmpty) ...[
                  const SizedBox(height: 8),
                  _MediaGrid(files: message.files),
                ],

                // Reasoning dropdown
                if ((message.reasoningContent ?? '').trim().isNotEmpty) ...[
                  const SizedBox(height: 8),
                  ReasoningDropdown(
                    reasoning: message.reasoningContent!.trim(),
                    isStreaming: isStreaming,
                  ),
                ],

                // Bottom toolbar
                Padding(
                  padding: const EdgeInsets.only(top: 6),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Row(
                        children: [
                          if (message.versions.length > 1) ...[
                            MessageVersionSwitcher(
                              message: message,
                              onSwitchVersion: onSwitchVersion,
                            ),
                            const SizedBox(width: 8),
                          ],
                          if (onCopy != null)
                            IconButton(
                              visualDensity: VisualDensity.compact,
                              iconSize: 18,
                              tooltip: tl('Copy'),
                              icon: const Icon(Icons.copy),
                              onPressed: onCopy,
                            ),
                          if (onRegenerate != null)
                            IconButton(
                              visualDensity: VisualDensity.compact,
                              iconSize: 18,
                              tooltip: tl('Regenerate'),
                              icon: const Icon(Icons.refresh),
                              onPressed: onRegenerate,
                            ),
                        ],
                      ),
                      PopupMenuButton<String>(
                        tooltip: tl('More'),
                        iconSize: 18,
                        icon: const Icon(Icons.more_vert),
                        onSelected: (value) {
                          switch (value) {
                            case 'edit':
                              onEdit?.call();
                              break;
                            case 'delete':
                              onDelete?.call();
                              break;
                          }
                        },
                        itemBuilder: (context) => [
                          PopupMenuItem(value: 'edit', child: Text(tl('Edit'))),
                          PopupMenuItem(
                            value: 'delete',
                            child: Text(tl('Delete')),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  void _showContextMenu(BuildContext context, Offset globalPos) async {
    final overlay = Overlay.of(context).context.findRenderObject() as RenderBox;
    final selected = await showMenu<String>(
      context: context,
      position: RelativeRect.fromLTRB(
        globalPos.dx,
        globalPos.dy,
        overlay.size.width - globalPos.dx,
        overlay.size.height - globalPos.dy,
      ),
      items: [
        PopupMenuItem(value: 'edit', child: Text(tl('Edit'))),
        PopupMenuItem(value: 'delete', child: Text(tl('Delete'))),
      ],
    );

    switch (selected) {
      case 'edit':
        onEdit?.call();
        break;
      case 'delete':
        onDelete?.call();
        break;
    }
  }
}

/// Widget hiển thị lưới media
class _MediaGrid extends StatelessWidget {
  final List<String> files;

  const _MediaGrid({required this.files});

  @override
  Widget build(BuildContext context) {
    final size = _computeTileSize(files.length);

    return Wrap(
      spacing: 8,
      runSpacing: 8,
      children: files.map((path) {
        final isImg = _isImagePath(path);
        return ClipRRect(
          borderRadius: BorderRadius.circular(8),
          child: Container(
            width: size,
            height: size,
            color: Theme.of(context).colorScheme.surface,
            child: isImg
                ? ThemeAwareImage(
                    child: Image.file(
                      File(path),
                      fit: BoxFit.cover,
                      errorBuilder: (c, e, s) => _MediaIconTile(path: path),
                    ),
                  )
                : _MediaIconTile(path: path),
          ),
        );
      }).toList(),
    );
  }

  double _computeTileSize(int count) {
    if (count <= 1) return 220;
    if (count == 2) return 140;
    if (count == 3) return 110;
    return 96;
  }

  bool _isImagePath(String path) {
    final lower = path.toLowerCase();
    return lower.endsWith('.png') ||
        lower.endsWith('.jpg') ||
        lower.endsWith('.jpeg') ||
        lower.endsWith('.gif') ||
        lower.endsWith('.webp') ||
        lower.endsWith('.bmp');
  }
}

/// Widget hiển thị icon cho media không phải ảnh
class _MediaIconTile extends StatelessWidget {
  final String path;

  const _MediaIconTile({required this.path});

  @override
  Widget build(BuildContext context) {
    final name = path.split('/').last;

    return Container(
      padding: const EdgeInsets.all(8),
      color: Theme.of(context).colorScheme.surfaceContainerHighest,
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(
            Icons.insert_drive_file,
            size: 28,
            color: Theme.of(context).iconTheme.color,
          ),
          const SizedBox(height: 6),
          Text(
            name,
            maxLines: 1,
            overflow: TextOverflow.ellipsis,
            style: Theme.of(context).textTheme.labelSmall,
          ),
        ],
      ),
    );
  }
}
